development:
  host: localhost
  database: twiliotest_development

test:
  host: localhost
  database: twiliotest_test


# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
  database: twiliotest_prod
  # slaves: khghjghj
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
